###
GET http://localhost:8080/owners/all

###
GET http://localhost:8080/address/all


###
GET http://localhost:8080/address/byId/100



###
GET http://localhost:8080/cats/join


###
GET http://localhost:8080/cats/graph


###
GET http://localhost:8080/cats/byownername/irina


###
GET http://localhost:8080/cats/ownerbycatname/barsik/



###
GET http://localhost:8080/cats/byownercity/Prague



###