micronaut:
  application:
    name: micronautJpaTest1
datasources:
  default:
    url: jdbc:mysql://localhost:3306/jbtests?serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: irina
    password: jolt
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update
